

class Const:


# Distribution of players
	PLAYERS_PER_TABLE = 10
	MIN_BOTS_PER_TABLE = 2
	MAX_HUMANS_PER_TABLE = (PLAYERS_PER_TABLE-MIN_BOTS_PER_TABLE)
	INSTANCES_PER_PLAYER = 8

# Game constants
	ROUNDS_PER_PHASE = 3
	PHASES_PER_GAME = 2
	STARTING_WEALTH = 100
	STARTING_BOMBS = 0

# Misc constants
	RANDOM_ID_LEN = 4