
class Const:


# Distribution of players
	PLAYERS_PER_TABLE = 10
	MIN_BOTS_PER_TABLE = 2
	MAX_HUMANS_PER_TABLE = (PLAYERS_PER_TABLE-MIN_BOTS_PER_TABLE)
    INSTANCES_PER_PLAYER = 15

# Game constants
    ROUNDS_PER_PHASE = 15
    PHASES_PER_GAME = 20
	STARTING_WEALTH = 100

# Misc constants
    RANDOM_ID_LEN = 10